// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WizCo.Infra.Data.Context;

#nullable disable

namespace WizCo.Infra.Data.Migrations
{
    [DbContext(typeof(PedidoDbContext))]
    [Migration("20260527012626_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WizCo.Core.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItensPedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecoUnitario = 4500m,
                            ProdutoNome = "Notebook Dell Inspiron",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecoUnitario = 7999m,
                            ProdutoNome = "iPhone 15 Pro",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("23333333-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecoUnitario = 3200m,
                            ProdutoNome = "Smart TV Samsung 55",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("24444444-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecoUnitario = 4200m,
                            ProdutoNome = "PlayStation 5",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("25555555-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecoUnitario = 550m,
                            ProdutoNome = "Mouse Logitech MX Master 3",
                            Quantidade = 2
                        },
                        new
                        {
                            Id = new Guid("26666666-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PrecoUnitario = 1800m,
                            ProdutoNome = "Monitor LG Ultrawide",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("27777777-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("77777777-7777-7777-7777-777777777777"),
                            PrecoUnitario = 350m,
                            ProdutoNome = "Teclado Mecânico Redragon",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("28888888-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("88888888-8888-8888-8888-888888888888"),
                            PrecoUnitario = 3200m,
                            ProdutoNome = "Apple Watch Series 9",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("29999999-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PrecoUnitario = 1400m,
                            ProdutoNome = "Cadeira Gamer ThunderX3",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("2aaaaaaa-1111-1111-1111-111111111111"),
                            PedidoId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PrecoUnitario = 299m,
                            ProdutoNome = "Echo Dot Alexa",
                            Quantidade = 3
                        });
                });

            modelBuilder.Entity("WizCo.Core.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ClienteNome = "João Silva",
                            DataCriacao = new DateTime(2026, 5, 7, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9861),
                            Status = "Pago",
                            ValorTotal = 4500m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClienteNome = "Maria Oliveira",
                            DataCriacao = new DateTime(2026, 5, 9, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9875),
                            Status = "Novo",
                            ValorTotal = 7999m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ClienteNome = "Carlos Souza",
                            DataCriacao = new DateTime(2026, 5, 10, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9880),
                            Status = "Cancelado",
                            ValorTotal = 3200m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ClienteNome = "Fernanda Lima",
                            DataCriacao = new DateTime(2026, 5, 12, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9884),
                            Status = "Pago",
                            ValorTotal = 4200m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ClienteNome = "Ricardo Mendes",
                            DataCriacao = new DateTime(2026, 5, 13, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9889),
                            Status = "Novo",
                            ValorTotal = 1100m
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            ClienteNome = "Patrícia Gomes",
                            DataCriacao = new DateTime(2026, 5, 14, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9893),
                            Status = "Pago",
                            ValorTotal = 1800m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            ClienteNome = "Lucas Ferreira",
                            DataCriacao = new DateTime(2026, 5, 15, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9897),
                            Status = "Cancelado",
                            ValorTotal = 350m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            ClienteNome = "Juliana Costa",
                            DataCriacao = new DateTime(2026, 5, 16, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9900),
                            Status = "Novo",
                            ValorTotal = 3200m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ClienteNome = "André Martins",
                            DataCriacao = new DateTime(2026, 5, 17, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9907),
                            Status = "Pago",
                            ValorTotal = 1400m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ClienteNome = "Camila Rocha",
                            DataCriacao = new DateTime(2026, 5, 18, 1, 26, 21, 113, DateTimeKind.Utc).AddTicks(9912),
                            Status = "Novo",
                            ValorTotal = 897m
                        });
                });

            modelBuilder.Entity("WizCo.Infra.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WizCo.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WizCo.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WizCo.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WizCo.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WizCo.Core.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("WizCo.Core.Domain.Entities.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WizCo.Core.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
